[project]
name = "mcp-monitor-server"
version = "0.1.0"
description = "An MCP server that monitors system events, such as file changes, and sends notifications to an MCP client"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []
